[package]
name = "dump"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web 框架
actix-web = "4.4"

# 序列化和反序列化支持
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 时间处理库
chrono = "0.4"
